import torch
from nnunetv2.training.loss.deep_supervision import DeepSupervisionWrapper
from nnunetv2.training.nnUNetTrainer.nnUNetTrainer import nnUNetTrainer
from nnunetv2.training.loss.boundary_loss import DC_and_BD_loss
from nnunetv2.training.loss.dice import get_tp_fp_fn_tn
import numpy as np
import SimpleITK as sitk
from torch import autocast

class nnUNetTrainerBDLoss(nnUNetTrainer):
    """
    Trainer class for boundary steering loss, which compares the Signed Distance Function from the
    target (clamped to [-10,+10] and normalized to [-1,+1]) to the probabilities generated by the
    model.
    """
    def __init__(self, plans: dict, configuration: str, fold: int, dataset_json: dict,
                 device: torch.device = torch.device('cuda'), **kwargs):
        super().__init__(plans, configuration, fold, dataset_json, device, **kwargs)

    def _build_loss(self):
        assert not self.label_manager.has_regions, "regions not supported by this trainer"
        
        '''loss = DC_and_CE_and_BD_loss({'batch_dice': self.configuration_manager.batch_dice,
            'smooth': 1e-5, 'do_bg': False, 'ddp': self.is_ddp}, {}, weight_ce=1, weight_dice=1, weight_bound=0.01,
            ignore_label=self.label_manager.ignore_label
        )'''
        
        loss = DC_and_BD_loss({'batch_dice': self.configuration_manager.batch_dice,
            'smooth': 1e-5, 'do_bg': False, 'ddp': self.is_ddp}, weight_dice=1, weight_bound=0.01,
            ignore_label=self.label_manager.ignore_label
        )
        # we give each output a weight which decreases exponentially (division by 2) as the resolution decreases
        # this gives higher resolution outputs more weight in the loss
        if self.enable_deep_supervision:
            deep_supervision_scales = self._get_deep_supervision_scales()
            weights = np.array([1 / (2**i) for i in range(len(deep_supervision_scales))])
            weights[-1] = 0

            # we don't use the lowest 2 outputs. Normalize weights so that they sum to 1
            weights = weights / weights.sum()
            # now wrap the loss
            loss = DeepSupervisionWrapper(loss, weights)
        return loss
    
    def compute_sdf_batch(self, target_tensor):
        """
        Computes the Signed Distance Function for a batch of tensors.
        Input: (B, 1, H, W) or (B, 1, D, H, W) on GPU/CPU
        Output: (B, 1, H, W) or (B, 1, D, H, W) on self.device
        """

        """
        SDF follows definition by nnSAM (https://aapm.onlinelibrary.wiley.com/doi/10.1002/mp.17481).
        Li Y, Jing B, Li Z, Wang J, Zhang Y. Plug-and-play segment anything model improves
        nnUNet performance. Med Phys. 2025 Feb;52(2):899-912. doi: 10.1002/mp.17481.
        Epub 2024 Oct 28. PMID: 39466578; PMCID: PMC11788268.
        """

        if isinstance(target_tensor, list):
            sdf_final_list = []
            for target in target_tensor:
                sdf_list = []
                for i in range(target.shape[0]):
                    # Extract single volume/image from batch
                    mask_slice = target[i, 0].to(torch.uint8)
                    
                    # SimpleITK logic
                    sitk_img = sitk.GetImageFromArray(mask_slice)
                    sdf_filter = sitk.SignedMaurerDistanceMapImageFilter()
                    sdf_filter.SetInsideIsPositive(False)
                    sdf_filter.SetSquaredDistance(False)
                    sdf_filter.SetUseImageSpacing(True)
                    
                    sdf_img = sdf_filter.Execute(sitk_img)
                    arr = sitk.GetArrayFromImage(sdf_img)
                    arr = arr / np.max(np.abs(arr) + 1e-6)
                    sdf_list.append(arr)

                # Stack
                sdf_batch = np.stack(sdf_list)[:, np.newaxis, ...]
                sdf_final_list.append(torch.from_numpy(sdf_batch))
            return sdf_final_list

        else:

            sdf_list = []
            for i in range(target_tensor.shape[0]):
                # Extract single volume/image from batch
                mask_slice = target_tensor[i, 0].to(torch.uint8)
                
                # SimpleITK logic
                sitk_img = sitk.GetImageFromArray(mask_slice)
                sdf_filter = sitk.SignedMaurerDistanceMapImageFilter()
                sdf_filter.SetInsideIsPositive(False)
                sdf_filter.SetSquaredDistance(False)
                sdf_filter.SetUseImageSpacing(True)
                
                sdf_img = sdf_filter.Execute(sitk_img)
                arr = sitk.GetArrayFromImage(sdf_img)
                arr = arr / np.max(np.abs(arr) + 1e-6)
                sdf_list.append(arr)

            # Stack
            sdf_batch = np.stack(sdf_list)[:, np.newaxis, ...]
            return torch.from_numpy(sdf_batch)
    
    def train_step(self, batch: dict) -> dict:
        data = batch['data']
        target = batch['target']
        
        distance_map = self.compute_sdf_batch(target)

        data = data.to(self.device, non_blocking=True)
        if isinstance(target, list):
            target = [i.to(self.device, non_blocking=True) for i in target]
            distance_map = [i.to(self.device, non_blocking=True) for i in distance_map]
        else:
            target = target.to(self.device, non_blocking=True)
            distance_map = distance_map.to(self.device, non_blocking=True)

        self.optimizer.zero_grad(set_to_none=True)
        # If the device_type is 'cpu' then it's slow as heck and needs to be disabled.
        # If the device_type is 'mps' then it will complain that mps is not implemented, even if enabled=False is set. Whyyyyyyy. (this is why we don't make use of enabled=False)
        # So autocast will only be active if we have a cuda device.
        with autocast(self.device.type, enabled=True) if self.device.type == 'cuda' else dummy_context():
            output = self.network(data)
            # del data
            l = self.loss(output, target, distance_map)

        if self.grad_scaler is not None:
            self.grad_scaler.scale(l).backward()
            self.grad_scaler.unscale_(self.optimizer)
            torch.nn.utils.clip_grad_norm_(self.network.parameters(), 12)
            self.grad_scaler.step(self.optimizer)
            self.grad_scaler.update()
        else:
            l.backward()
            torch.nn.utils.clip_grad_norm_(self.network.parameters(), 12)
            self.optimizer.step()
        return {'loss': l.detach().cpu().numpy()}
    
    def validation_step(self, batch: dict) -> dict:
        data = batch['data']
        target = batch['target']

        distance_map = self.compute_sdf_batch(target)

        data = data.to(self.device, non_blocking=True)
        if isinstance(target, list):
            target = [i.to(self.device, non_blocking=True) for i in target]
            distance_map = [i.to(self.device, non_blocking=True) for i in distance_map]
        else:
            target = target.to(self.device, non_blocking=True)
            distance_map = distance_map.to(self.device, non_blocking=True)

        # If the device_type is 'cpu' then it's slow as heck and needs to be disabled.
        # If the device_type is 'mps' then it will complain that mps is not implemented, even if enabled=False is set. Whyyyyyyy. (this is why we don't make use of enabled=False)
        # So autocast will only be active if we have a cuda device.
        with autocast(self.device.type, enabled=True) if self.device.type == 'cuda' else dummy_context():
            output = self.network(data)
            del data
            l = self.loss(output, target, distance_map)

        # only need the output with the highest output resolution (if DS enabled)
        if self.enable_deep_supervision:
            output = output[0]
            target = target[0]

        # the following is needed for online evaluation. Fake dice (green line)
        axes = [0] + list(range(2, output.ndim))

        if self.label_manager.has_regions:
            predicted_segmentation_onehot = (torch.sigmoid(output) > 0.5).long()
        else:
            # no need for softmax
            output_seg = output.argmax(1)[:, None]
            predicted_segmentation_onehot = torch.zeros(output.shape, device=output.device, dtype=torch.float16)
            predicted_segmentation_onehot.scatter_(1, output_seg, 1)
            del output_seg

        if self.label_manager.has_ignore_label:
            if not self.label_manager.has_regions:
                mask = (target != self.label_manager.ignore_label).float()
                target[target == self.label_manager.ignore_label] = 0
            else:
                if target.dtype == torch.bool:
                    mask = ~target[:, -1:]
                else:
                    mask = 1 - target[:, -1:]
                target = target[:, :-1]
        else:
            mask = None

        tp, fp, fn, _ = get_tp_fp_fn_tn(predicted_segmentation_onehot, target, axes=axes, mask=mask)

        tp_hard = tp.detach().cpu().numpy()
        fp_hard = fp.detach().cpu().numpy()
        fn_hard = fn.detach().cpu().numpy()
        if not self.label_manager.has_regions:
            # if we train with regions all segmentation heads predict some kind of foreground. In conventional
            # (softmax training) there needs to be one output for the background. We are not interested in the
            # background Dice
            # [1:] in order to remove background
            tp_hard = tp_hard[1:]
            fp_hard = fp_hard[1:]
            fn_hard = fn_hard[1:]

        return {'loss': l.detach().cpu().numpy(), 'tp_hard': tp_hard, 'fp_hard': fp_hard, 'fn_hard': fn_hard}


""" Variations of weight hiperparameter for the combination of Dice loss and Boundary loss """

class nnUNetTrainer001BDLoss(nnUNetTrainerBDLoss):
    def __init__(self, plans: dict, configuration: str, fold: int, dataset_json: dict,
                 device: torch.device = torch.device('cuda'), **kwargs):
        super().__init__(plans, configuration, fold, dataset_json, device, **kwargs)

    def _build_loss(self):
        assert not self.label_manager.has_regions, "regions not supported by this trainer"
        
        '''loss = DC_and_CE_and_BD_loss({'batch_dice': self.configuration_manager.batch_dice,
            'smooth': 1e-5, 'do_bg': False, 'ddp': self.is_ddp}, {}, weight_ce=1, weight_dice=1, weight_bound=0.01,
            ignore_label=self.label_manager.ignore_label
        )'''
        
        loss = DC_and_BD_loss({'batch_dice': self.configuration_manager.batch_dice,
            'smooth': 1e-5, 'do_bg': False, 'ddp': self.is_ddp}, weight_dice=1, weight_bound=0.01,
            ignore_label=self.label_manager.ignore_label
        )
        # we give each output a weight which decreases exponentially (division by 2) as the resolution decreases
        # this gives higher resolution outputs more weight in the loss
        if self.enable_deep_supervision:
            deep_supervision_scales = self._get_deep_supervision_scales()
            weights = np.array([1 / (2**i) for i in range(len(deep_supervision_scales))])
            weights[-1] = 0

            # we don't use the lowest 2 outputs. Normalize weights so that they sum to 1
            weights = weights / weights.sum()
            # now wrap the loss
            loss = DeepSupervisionWrapper(loss, weights)
        return loss

class nnUNetTrainer008BDLoss(nnUNetTrainerBDLoss):
    def __init__(self, plans: dict, configuration: str, fold: int, dataset_json: dict,
                 device: torch.device = torch.device('cuda'), **kwargs):
        super().__init__(plans, configuration, fold, dataset_json, device, **kwargs)

    def _build_loss(self):
        assert not self.label_manager.has_regions, "regions not supported by this trainer"
        
        '''loss = DC_and_CE_and_BD_loss({'batch_dice': self.configuration_manager.batch_dice,
            'smooth': 1e-5, 'do_bg': False, 'ddp': self.is_ddp}, {}, weight_ce=1, weight_dice=1, weight_bound=0.01,
            ignore_label=self.label_manager.ignore_label
        )'''
        
        loss = DC_and_BD_loss({'batch_dice': self.configuration_manager.batch_dice,
            'smooth': 1e-5, 'do_bg': False, 'ddp': self.is_ddp}, weight_dice=1, weight_bound=0.08,
            ignore_label=self.label_manager.ignore_label
        )
        # we give each output a weight which decreases exponentially (division by 2) as the resolution decreases
        # this gives higher resolution outputs more weight in the loss
        if self.enable_deep_supervision:
            deep_supervision_scales = self._get_deep_supervision_scales()
            weights = np.array([1 / (2**i) for i in range(len(deep_supervision_scales))])
            weights[-1] = 0

            # we don't use the lowest 2 outputs. Normalize weights so that they sum to 1
            weights = weights / weights.sum()
            # now wrap the loss
            loss = DeepSupervisionWrapper(loss, weights)
        return loss

class nnUNetTrainer005BDLoss(nnUNetTrainerBDLoss):
    def __init__(self, plans: dict, configuration: str, fold: int, dataset_json: dict,
                 device: torch.device = torch.device('cuda'), **kwargs):
        super().__init__(plans, configuration, fold, dataset_json, device, **kwargs)

    def _build_loss(self):
        assert not self.label_manager.has_regions, "regions not supported by this trainer"
        
        '''loss = DC_and_CE_and_BD_loss({'batch_dice': self.configuration_manager.batch_dice,
            'smooth': 1e-5, 'do_bg': False, 'ddp': self.is_ddp}, {}, weight_ce=1, weight_dice=1, weight_bound=0.01,
            ignore_label=self.label_manager.ignore_label
        )'''
        
        loss = DC_and_BD_loss({'batch_dice': self.configuration_manager.batch_dice,
            'smooth': 1e-5, 'do_bg': False, 'ddp': self.is_ddp}, weight_dice=1, weight_bound=0.05,
            ignore_label=self.label_manager.ignore_label
        )
        # we give each output a weight which decreases exponentially (division by 2) as the resolution decreases
        # this gives higher resolution outputs more weight in the loss
        if self.enable_deep_supervision:
            deep_supervision_scales = self._get_deep_supervision_scales()
            weights = np.array([1 / (2**i) for i in range(len(deep_supervision_scales))])
            weights[-1] = 0

            # we don't use the lowest 2 outputs. Normalize weights so that they sum to 1
            weights = weights / weights.sum()
            # now wrap the loss
            loss = DeepSupervisionWrapper(loss, weights)
        return loss

class nnUNetTrainer006BDLoss(nnUNetTrainerBDLoss):
    def __init__(self, plans: dict, configuration: str, fold: int, dataset_json: dict,
                 device: torch.device = torch.device('cuda'), **kwargs):
        super().__init__(plans, configuration, fold, dataset_json, device, **kwargs)

    def _build_loss(self):
        assert not self.label_manager.has_regions, "regions not supported by this trainer"
        
        '''loss = DC_and_CE_and_BD_loss({'batch_dice': self.configuration_manager.batch_dice,
            'smooth': 1e-5, 'do_bg': False, 'ddp': self.is_ddp}, {}, weight_ce=1, weight_dice=1, weight_bound=0.01,
            ignore_label=self.label_manager.ignore_label
        )'''
        
        loss = DC_and_BD_loss({'batch_dice': self.configuration_manager.batch_dice,
            'smooth': 1e-5, 'do_bg': False, 'ddp': self.is_ddp}, weight_dice=1, weight_bound=0.06,
            ignore_label=self.label_manager.ignore_label
        )
        # we give each output a weight which decreases exponentially (division by 2) as the resolution decreases
        # this gives higher resolution outputs more weight in the loss
        if self.enable_deep_supervision:
            deep_supervision_scales = self._get_deep_supervision_scales()
            weights = np.array([1 / (2**i) for i in range(len(deep_supervision_scales))])
            weights[-1] = 0

            # we don't use the lowest 2 outputs. Normalize weights so that they sum to 1
            weights = weights / weights.sum()
            # now wrap the loss
            loss = DeepSupervisionWrapper(loss, weights)
        return loss

class nnUNetTrainer007BDLoss(nnUNetTrainerBDLoss):
    def __init__(self, plans: dict, configuration: str, fold: int, dataset_json: dict,
                 device: torch.device = torch.device('cuda'), **kwargs):
        super().__init__(plans, configuration, fold, dataset_json, device, **kwargs)

    def _build_loss(self):
        assert not self.label_manager.has_regions, "regions not supported by this trainer"
        
        '''loss = DC_and_CE_and_BD_loss({'batch_dice': self.configuration_manager.batch_dice,
            'smooth': 1e-5, 'do_bg': False, 'ddp': self.is_ddp}, {}, weight_ce=1, weight_dice=1, weight_bound=0.01,
            ignore_label=self.label_manager.ignore_label
        )'''
        
        loss = DC_and_BD_loss({'batch_dice': self.configuration_manager.batch_dice,
            'smooth': 1e-5, 'do_bg': False, 'ddp': self.is_ddp}, weight_dice=1, weight_bound=0.07,
            ignore_label=self.label_manager.ignore_label
        )
        # we give each output a weight which decreases exponentially (division by 2) as the resolution decreases
        # this gives higher resolution outputs more weight in the loss
        if self.enable_deep_supervision:
            deep_supervision_scales = self._get_deep_supervision_scales()
            weights = np.array([1 / (2**i) for i in range(len(deep_supervision_scales))])
            weights[-1] = 0

            # we don't use the lowest 2 outputs. Normalize weights so that they sum to 1
            weights = weights / weights.sum()
            # now wrap the loss
            loss = DeepSupervisionWrapper(loss, weights)
        return loss

class nnUNetTrainer0005BDLoss(nnUNetTrainerBDLoss):
    def __init__(self, plans: dict, configuration: str, fold: int, dataset_json: dict,
                 device: torch.device = torch.device('cuda'), **kwargs):
        super().__init__(plans, configuration, fold, dataset_json, device, **kwargs)

    def _build_loss(self):
        assert not self.label_manager.has_regions, "regions not supported by this trainer"
        
        '''loss = DC_and_CE_and_BD_loss({'batch_dice': self.configuration_manager.batch_dice,
            'smooth': 1e-5, 'do_bg': False, 'ddp': self.is_ddp}, {}, weight_ce=1, weight_dice=1, weight_bound=0.01,
            ignore_label=self.label_manager.ignore_label
        )'''
        
        loss = DC_and_BD_loss({'batch_dice': self.configuration_manager.batch_dice,
            'smooth': 1e-5, 'do_bg': False, 'ddp': self.is_ddp}, weight_dice=1, weight_bound=0.005,
            ignore_label=self.label_manager.ignore_label
        )
        # we give each output a weight which decreases exponentially (division by 2) as the resolution decreases
        # this gives higher resolution outputs more weight in the loss
        if self.enable_deep_supervision:
            deep_supervision_scales = self._get_deep_supervision_scales()
            weights = np.array([1 / (2**i) for i in range(len(deep_supervision_scales))])
            weights[-1] = 0

            # we don't use the lowest 2 outputs. Normalize weights so that they sum to 1
            weights = weights / weights.sum()
            # now wrap the loss
            loss = DeepSupervisionWrapper(loss, weights)
        return loss

"""Variation of training length """
class nnUNetTrainerBDLoss_100epochs(nnUNetTrainerBDLoss):
    def __init__(
        self,
        plans: dict,
        configuration: str,
        fold: int,
        dataset_json: dict,
        device: torch.device = torch.device("cuda"),
        **kwargs
    ):
        """used for debugging plans etc"""
        super().__init__(plans, configuration, fold, dataset_json, device, **kwargs)
        self.num_epochs = 100
